
version: '3'

services:
  app-server:
    container_name: chotuve-appserver
    build: .
    volumes:
      - .:/app
    ports:
      - 5000:5000
    environment:
      - DATABASE_DEV_URL=postgresql://franco_g:${PSQL_PASS}@localhost/chotuve-appserver-dev
      - DATABASE_PROD_URL=postgresql://franco_g:${PSQL_PASS}@localhost/chotuve-appserver-prod
      - APP_SETTINGS=config.DevelopmentConfig
