version: "3"

services:
    app-server:
        container_name: chotuve-appserver
        depends_on:
            - db
        build:
            context: .
            dockerfile: Dockerfile.dev
        restart: always
        ports:
            - "5000:5000" 
        volumes:
            - ./:/app
        env_file:
            - ./.env.dev
    db:
        image: postgres:12-alpine
        volumes:
            - ./postgres_data:/var/lib/postgresql/data/
        environment:
            - POSTGRES_USER=chotuve
            - POSTGRES_PASSWORD=chotuve
            - POSTGRES_DB=chotuve-appserver
