"""empty message

Revision ID: 0b2b402c19c7
Revises: 41a45eac2fea
Create Date: 2020-07-22 23:37:55.708959

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0b2b402c19c7'
down_revision = '41a45eac2fea'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('videos', sa.Column('cached_relevance', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('videos', 'cached_relevance')
    # ### end Alembic commands ###
