"""empty message

Revision ID: 10e6965ec4ba
Revises: 2fc0025249b2
Create Date: 2020-07-02 06:19:22.024102

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '10e6965ec4ba'
down_revision = '2fc0025249b2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('videos', 'likes')
    op.drop_column('videos', 'dislikes')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('videos', sa.Column('dislikes', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('videos', sa.Column('likes', sa.INTEGER(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
