"""empty message

Revision ID: 23dd7083d200
Revises: d48ffaf0c269
Create Date: 2020-07-01 17:27:30.022921

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '23dd7083d200'
down_revision = 'd48ffaf0c269'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('push_token', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'push_token')
    # ### end Alembic commands ###
