"""empty message

Revision ID: 352333637d13
Revises: fbb7180ee876
Create Date: 2020-06-30 21:05:16.252558

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '352333637d13'
down_revision = 'fbb7180ee876'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('chat_user1', sa.Integer(), nullable=False))
    op.add_column('messages', sa.Column('chat_user2', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('messages', 'chat_user2')
    op.drop_column('messages', 'chat_user1')
    # ### end Alembic commands ###
