"""empty message

Revision ID: 56165ff9e500
Revises: 
Create Date: 2020-05-21 04:28:53.741682

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '56165ff9e500'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('videos',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('title', sa.String(length=100), nullable=True),
                    sa.Column('description', sa.Text(), nullable=True),
                    sa.Column('uuid', sa.Integer(), nullable=False),
                    sa.Column('location', sa.String(
                        length=200), nullable=True),
                    sa.Column('is_private', sa.Boolean(), nullable=True),
                    sa.Column('likes', sa.Integer(), nullable=True),
                    sa.Column('dislikes', sa.Integer(), nullable=True),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('comments',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('uuid', sa.Integer(), nullable=False),
                    sa.Column('text', sa.Text(), nullable=True),
                    sa.Column('timestamp', sa.DateTime(), nullable=True),
                    sa.Column('parent_video', sa.Integer(), nullable=False),
                    sa.ForeignKeyConstraint(['parent_video'], ['videos.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('video_reactions',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('uuid', sa.Integer(), nullable=False),
                    sa.Column('likes_video', sa.Boolean(), nullable=False),
                    sa.Column('timestamp', sa.DateTime(), nullable=True),
                    sa.Column('parent_video', sa.Integer(), nullable=False),
                    sa.ForeignKeyConstraint(['parent_video'], ['videos.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('video_reactions')
    op.drop_table('comments')
    op.drop_table('videos')
    # ### end Alembic commands ###
