"""empty message

Revision ID: 98fd260fab21
Revises: bbf9683767ed
Create Date: 2020-05-26 02:34:50.267585

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '98fd260fab21'
down_revision = 'bbf9683767ed'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('requests',
                    sa.Column('sender_id', sa.Integer(), nullable=True),
                    sa.Column('recver_id', sa.Integer(), nullable=True),
                    sa.ForeignKeyConstraint(['recver_id'], ['users.id'], ),
                    sa.ForeignKeyConstraint(['sender_id'], ['users.id'], )
                    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('requests')
    # ### end Alembic commands ###
