"""empty message

Revision ID: b71c71b9eb64
Revises: a9b894b5ff2a
Create Date: 2020-07-25 23:58:38.473241

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b71c71b9eb64'
down_revision = 'a9b894b5ff2a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('http_responses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('path', sa.String(length=200), nullable=True),
    sa.Column('method', sa.String(length=100), nullable=True),
    sa.Column('response_code', sa.Integer(), nullable=True),
    sa.Column('client_ip', sa.String(length=20), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('http_responses')
    # ### end Alembic commands ###
