"""empty message

Revision ID: ba94c5c33b70
Revises: 7056f74fb292
Create Date: 2020-04-26 18:01:24.773601

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ba94c5c33b70'
down_revision = '7056f74fb292'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('video_reactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('likes_video', sa.Boolean(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('parent_video', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['parent_video'], ['videos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('video_reactions')
    # ### end Alembic commands ###
