"""empty message

Revision ID: d48ffaf0c269
Revises: 352333637d13
Create Date: 2020-06-30 21:12:08.062942

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd48ffaf0c269'
down_revision = '352333637d13'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'messages', 'chats', ['chat_user1', 'chat_user2'], ['user1_id', 'user2_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'messages', type_='foreignkey')
    # ### end Alembic commands ###
