"""empty message

Revision ID: fbb7180ee876
Revises: 1b8f7fda2968
Create Date: 2020-06-30 20:54:49.221583

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fbb7180ee876'
down_revision = '1b8f7fda2968'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('chats_user2_id_fkey', 'chats', type_='foreignkey')
    op.drop_constraint('chats_user1_id_fkey', 'chats', type_='foreignkey')
    op.drop_constraint('messages_recver_id_fkey', 'messages', type_='foreignkey')
    op.drop_constraint('messages_sender_id_fkey', 'messages', type_='foreignkey')
    op.drop_column('messages', 'parent_chat')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('parent_chat', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key('messages_sender_id_fkey', 'messages', 'users', ['sender_id'], ['id'])
    op.create_foreign_key('messages_recver_id_fkey', 'messages', 'users', ['recver_id'], ['id'])
    op.create_foreign_key('chats_user1_id_fkey', 'chats', 'users', ['user1_id'], ['id'])
    op.create_foreign_key('chats_user2_id_fkey', 'chats', 'users', ['user2_id'], ['id'])
    # ### end Alembic commands ###
