"""empty message

Revision ID: fd775370f4af
Revises: 3d8e58d7d5cb
Create Date: 2020-06-30 20:10:41.668038

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fd775370f4af'
down_revision = '3d8e58d7d5cb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comments', sa.Column('vid_time', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('comments', 'vid_time')
    # ### end Alembic commands ###
